"""Add tenant background color and font family

Revision ID: 1a0098ed4df2
Revises: adfc593a6011
Create Date: 2026-10-05 11:13:09.779967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0098ed4df2'
down_revision = 'adfc593a6011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default: tenants is a populated table, so these NOT NULL
    # columns need a value for existing rows, not just the ORM-level
    # Python default on the model (which only applies to new inserts).
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_color', sa.String(length=7), nullable=False, server_default='#f6f7f5'))
        batch_op.add_column(sa.Column('font_family', sa.String(length=20), nullable=False, server_default='system'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('font_family')
        batch_op.drop_column('background_color')

    # ### end Alembic commands ###
