"""Track last-paid date for idempotent billing cycle advances

Revision ID: 2696c50eab07
Revises: 596c823a290c
Create Date: 2026-10-08 14:45:38.062187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2696c50eab07'
down_revision = '596c823a290c'
branch_labels = None
depends_on = None


def upgrade():
    # Nullable, no backfill needed - None means "never recorded a
    # payment", which is simply true for every tenant/auditor until the
    # next time mark-paid (or resync) runs for them, and never
    # accidentally equals today's date.
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_paid_on', sa.Date(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_paid_on', sa.Date(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_paid_on')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('last_paid_on')

    # ### end Alembic commands ###
