"""Add e-invoice IRN/QR hook columns to invoices

Revision ID: 2fdf4fcdb990
Revises: 9f9e6f6c2d80
Create Date: 2026-10-05 09:12:29.412299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fdf4fcdb990'
down_revision = '9f9e6f6c2d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('irn', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('irn_ack_number', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('irn_ack_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('qr_code_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('qr_code_data')
        batch_op.drop_column('irn_ack_date')
        batch_op.drop_column('irn_ack_number')
        batch_op.drop_column('irn')

    # ### end Alembic commands ###
