"""Separate RCM GST columns on invoices and invoice_lines

Revision ID: 69bd39a34e71
Revises: 6efb37a835be
Create Date: 2026-10-06 06:58:53.382715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69bd39a34e71'
down_revision = '6efb37a835be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rcgst_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('rsgst_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('rigst_amount', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_rcgst', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('total_rsgst', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('total_rigst', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###

    # Existing RCM_INVOICE rows were created before these columns existed,
    # so their tax still sits in cgst/sgst/igst (shared with a Tax
    # Invoice) - move it into the new rc* columns so it stops counting as
    # this tenant's own output tax in GSTR-3B (see app.reports.gstr).
    op.execute("""
        UPDATE invoice_lines SET
            rcgst_amount = cgst_amount, rsgst_amount = sgst_amount, rigst_amount = igst_amount,
            cgst_amount = 0, sgst_amount = 0, igst_amount = 0
        WHERE invoice_id IN (SELECT id FROM invoices WHERE document_type = 'RCM_INVOICE')
    """)
    op.execute("""
        UPDATE invoices SET
            total_rcgst = total_cgst, total_rsgst = total_sgst, total_rigst = total_igst,
            total_cgst = 0, total_sgst = 0, total_igst = 0
        WHERE document_type = 'RCM_INVOICE'
    """)


def downgrade():
    # Restore the pre-migration state (RCM tax back in cgst/sgst/igst)
    # before the rc* columns holding it are dropped below.
    op.execute("""
        UPDATE invoices SET
            total_cgst = total_rcgst, total_sgst = total_rsgst, total_igst = total_rigst
        WHERE document_type = 'RCM_INVOICE'
    """)
    op.execute("""
        UPDATE invoice_lines SET
            cgst_amount = rcgst_amount, sgst_amount = rsgst_amount, igst_amount = rigst_amount
        WHERE invoice_id IN (SELECT id FROM invoices WHERE document_type = 'RCM_INVOICE')
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('total_rigst')
        batch_op.drop_column('total_rsgst')
        batch_op.drop_column('total_rcgst')

    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.drop_column('rigst_amount')
        batch_op.drop_column('rsgst_amount')
        batch_op.drop_column('rcgst_amount')

    # ### end Alembic commands ###
