"""Store uploaded images in the database instead of local disk

Revision ID: 6b372d445836
Revises: ee6a6d5b47a3
Create Date: 2026-10-05 13:26:40.314910

"""
import os

from alembic import op
import sqlalchemy as sa

from flask import current_app

# revision identifiers, used by Alembic.
revision = '6b372d445836'
down_revision = 'ee6a6d5b47a3'
branch_labels = None
depends_on = None

_CONTENT_TYPES = {
    "png": "image/png",
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "gif": "image/gif",
    "webp": "image/webp",
}


def upgrade():
    bind = op.get_bind()

    # Read the old disk-path values (and, best-effort, the files
    # themselves if this environment's disk still has them) before the
    # columns that hold those paths are dropped below.
    old_tenant_logos = bind.execute(sa.text("SELECT id, logo_path FROM tenants WHERE logo_path IS NOT NULL")).fetchall()
    old_product_images = bind.execute(sa.text("SELECT id, image_path FROM products WHERE image_path IS NOT NULL")).fetchall()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_products_image_id', 'uploaded_images', ['image_id'], ['id'])
        batch_op.drop_column('image_path')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tenants_logo_image_id', 'uploaded_images', ['logo_image_id'], ['id'])
        batch_op.drop_column('logo_path')

    # ### end Alembic commands ###

    # Best-effort carry-over: a file this environment's disk still has
    # becomes a database row, so a logo/photo already uploaded before
    # this migration isn't lost. One that's already gone (a redeploy or
    # restart already dropped it - the exact bug this migration fixes
    # for good) is simply left unset; that tenant/product needs a
    # one-time re-upload, same as if this migration had never run.
    static_root = os.path.join(current_app.root_path, "static")

    def _carry_over(relative_path):
        full_path = os.path.join(static_root, relative_path)
        if not os.path.isfile(full_path):
            return None
        ext = relative_path.rsplit(".", 1)[-1].lower() if "." in relative_path else ""
        content_type = _CONTENT_TYPES.get(ext)
        if not content_type:
            return None
        with open(full_path, "rb") as fh:
            data = fh.read()
        return bind.execute(
            sa.text("INSERT INTO uploaded_images (content_type, data, created_at, updated_at) "
                    "VALUES (:ct, :data, now(), now()) RETURNING id"),
            {"ct": content_type, "data": data},
        ).scalar()

    for tenant_id, logo_path in old_tenant_logos:
        new_id = _carry_over(logo_path)
        if new_id:
            bind.execute(sa.text("UPDATE tenants SET logo_image_id = :img_id WHERE id = :id"), {"img_id": new_id, "id": tenant_id})

    for product_id, image_path in old_product_images:
        new_id = _carry_over(image_path)
        if new_id:
            bind.execute(sa.text("UPDATE products SET image_id = :img_id WHERE id = :id"), {"img_id": new_id, "id": product_id})


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_tenants_logo_image_id', type_='foreignkey')
        batch_op.drop_column('logo_image_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_products_image_id', type_='foreignkey')
        batch_op.drop_column('image_id')

    op.drop_table('uploaded_images')
    # ### end Alembic commands ###
