"""Branch-billed invoicing: branch type, invoice branch link, drop stock grace qty

Revision ID: 6efb37a835be
Revises: 9d65f2dce8bd
Create Date: 2026-10-06 06:22:36.125867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efb37a835be'
down_revision = '9d65f2dce8bd'
branch_labels = None
depends_on = None


_BRANCH_TYPE = sa.Enum('OWNED', 'THIRD_PARTY', name='branch_type')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # A brand-new Postgres ENUM type - unlike a column added within a
    # CREATE TABLE, ALTER TABLE ADD COLUMN doesn't auto-issue CREATE TYPE,
    # so it has to be created explicitly before it's referenced below.
    _BRANCH_TYPE.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_invoices_branch_user_id'), ['branch_user_id'], unique=False)
        batch_op.create_foreign_key('fk_invoices_branch_user_id_users', 'users', ['branch_user_id'], ['id'])

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('stock_grace_qty')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_type', _BRANCH_TYPE, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('branch_type')
    _BRANCH_TYPE.drop(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_grace_qty', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoices_branch_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoices_branch_user_id'))
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('branch_user_id')

    # ### end Alembic commands ###
