"""Add branch stock allocations and tenant stock grace qty

Revision ID: 9d65f2dce8bd
Revises: 6b372d445836
Create Date: 2026-10-06 05:27:58.896554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d65f2dce8bd'
down_revision = '6b372d445836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_stock_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('allocated_date', sa.Date(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branch_stock_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_stock_allocations_allocated_date'), ['allocated_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_stock_allocations_branch_user_id'), ['branch_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_stock_allocations_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_stock_allocations_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_grace_qty', sa.Integer(), nullable=False, server_default='10'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('stock_grace_qty')

    with op.batch_alter_table('branch_stock_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_stock_allocations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_branch_stock_allocations_product_id'))
        batch_op.drop_index(batch_op.f('ix_branch_stock_allocations_branch_user_id'))
        batch_op.drop_index(batch_op.f('ix_branch_stock_allocations_allocated_date'))

    op.drop_table('branch_stock_allocations')
    # ### end Alembic commands ###
