"""Add credit_debit_notes and note_lines

Revision ID: 9f9e6f6c2d80
Revises: 7c7a852b2b76
Create Date: 2026-10-05 05:57:19.262581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9f9e6f6c2d80'
down_revision = '7c7a852b2b76'
branch_labels = None
depends_on = None

# document_type already exists as a Postgres ENUM type (created by the
# initial migration for invoice_series/invoices/pos_bills) - create_type=
# False tells Alembic to reuse it instead of re-issuing CREATE TYPE, which
# fails with "type already exists".
_DOCUMENT_TYPE = postgresql.ENUM(
    'TAX_INVOICE', 'BILL_OF_SUPPLY', 'EXPORT_INVOICE_IGST', 'EXPORT_INVOICE_LUT',
    'RCM_INVOICE', 'DELIVERY_CHALLAN', 'RECEIPT_VOUCHER', 'REFUND_VOUCHER',
    'CREDIT_NOTE', 'DEBIT_NOTE', 'POS_BILL',
    name='document_type', create_type=False,
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_debit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gstin_id', sa.Integer(), nullable=False),
    sa.Column('invoice_series_id', sa.Integer(), nullable=False),
    sa.Column('note_number', sa.String(length=64), nullable=False),
    sa.Column('document_type', _DOCUMENT_TYPE, nullable=False),
    sa.Column('original_invoice_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_snapshot', sa.JSON(), nullable=False),
    sa.Column('place_of_supply_state_code', sa.String(length=2), nullable=False),
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'VOID', name='note_status'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_taxable_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cgst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_sgst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_igst', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('round_off', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by_id', sa.Integer(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['gstin_id'], ['gstins.id'], ),
    sa.ForeignKeyConstraint(['invoice_series_id'], ['invoice_series.id'], ),
    sa.ForeignKeyConstraint(['original_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'note_number', name='uq_note_tenant_number')
    )
    with op.batch_alter_table('credit_debit_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_debit_notes_gstin_id'), ['gstin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_debit_notes_note_number'), ['note_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_debit_notes_original_invoice_id'), ['original_invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_debit_notes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('note_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('hsn_or_sac_code', sa.String(length=8), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['credit_debit_notes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('note_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_lines_note_id'), ['note_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_lines_note_id'))

    op.drop_table('note_lines')
    with op.batch_alter_table('credit_debit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_debit_notes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_credit_debit_notes_original_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_credit_debit_notes_note_number'))
        batch_op.drop_index(batch_op.f('ix_credit_debit_notes_gstin_id'))

    op.drop_table('credit_debit_notes')
    # ### end Alembic commands ###

    # note_status is only used here - unlike document_type, it's safe (and
    # necessary, per Postgres: ENUM types outlive the tables that used
    # them) to drop on downgrade.
    sa.Enum(name='note_status').drop(op.get_bind(), checkfirst=True)
