"""Add tenant branding and product image columns

Revision ID: adfc593a6011
Revises: 2fdf4fcdb990
Create Date: 2026-10-05 10:22:53.730829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfc593a6011'
down_revision = '2fdf4fcdb990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_path', sa.String(length=255), nullable=True))
        # server_default: tenants is a populated table, so the NOT NULL
        # columns need a value for existing rows, not just the ORM-level
        # Python default on the model (which only applies to new inserts).
        batch_op.add_column(sa.Column('primary_color', sa.String(length=7), nullable=False, server_default='#1f7a4d'))
        batch_op.add_column(sa.Column('login_slug', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('default_receipt_format', sa.String(length=10), nullable=False, server_default='3in'))
        batch_op.create_unique_constraint('uq_tenants_login_slug', ['login_slug'])

    # ### end Alembic commands ###

    # Backfill a slug for every tenant that already exists, so the branded
    # login link works immediately for them too, not just new onboardings.
    op.execute(
        "UPDATE tenants SET login_slug = lower(regexp_replace(legal_name, '[^a-zA-Z0-9]+', '-', 'g')) "
        "|| '-' || id::text WHERE login_slug IS NULL"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tenants_login_slug', type_='unique')
        batch_op.drop_column('default_receipt_format')
        batch_op.drop_column('login_slug')
        batch_op.drop_column('primary_color')
        batch_op.drop_column('logo_path')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
