"""Add tenant access expiry and monthly billing due date

Revision ID: c530a2d610fa
Revises: 69bd39a34e71
Create Date: 2026-10-06 13:44:41.095666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c530a2d610fa'
down_revision = '69bd39a34e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_until', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('next_billing_due', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('next_billing_due')
        batch_op.drop_column('valid_until')

    # ### end Alembic commands ###
