"""Add tenant text color, clean up whitespace customer GSTINs

Revision ID: ee6a6d5b47a3
Revises: 1a0098ed4df2
Create Date: 2026-10-05 11:46:20.863524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6a6d5b47a3'
down_revision = '1a0098ed4df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('text_color', sa.String(length=7), nullable=False, server_default='#1f2a24')
        )

    # ### end Alembic commands ###

    # Backfill a *contrasting* text color for tenants that already had a
    # background set, rather than leaving every tenant on the dark
    # default - a tenant who'd already picked a dark background would
    # otherwise go instantly unreadable (dark text on dark background)
    # the moment this migration runs, before they ever touch the new
    # Settings field. New tenants (and anyone who explicitly saves
    # Settings afterwards) aren't touched by this - it's a one-time seed.
    bind = op.get_bind()
    rows = bind.execute(sa.text("SELECT id, background_color FROM tenants")).fetchall()
    for tenant_id, background_hex in rows:
        if not background_hex or len(background_hex) != 7:
            continue
        r, g, b = int(background_hex[1:3], 16), int(background_hex[3:5], 16), int(background_hex[5:7], 16)
        luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255
        text_color = "#1f2a24" if luminance > 0.5 else "#f5f6f4"
        bind.execute(
            sa.text("UPDATE tenants SET text_color = :c WHERE id = :id"),
            {"c": text_color, "id": tenant_id},
        )

    # A whitespace-only GSTIN (e.g. " ") is truthy in Python, so it was
    # silently misclassifying these customers as B2B (has a GSTIN)
    # instead of B2C in the GSTR-1 report - normalize existing bad data
    # the same way the form now does for new entries.
    op.execute("UPDATE customers SET gstin = NULL WHERE gstin IS NOT NULL AND trim(gstin) = ''")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('text_color')

    # ### end Alembic commands ###
